import type { Prisma } from "@prisma/client";

export type MobilityPaymentMethod =
  | "CASH"
  | "DIGITAL";

export type MobilityCashObligationStatus =
  | "OPEN"
  | "PARTIALLY_SETTLED"
  | "SETTLED"
  | "CANCELLED";

export interface CreateMobilityCashObligationInput {
  organizationId: string;
  driverId: string;
  rideId: string;

  currency: string;

  grossFareMinor: bigint;
  commissionRateBps: number;
  commissionAmountMinor: bigint;

  policyKey: string;
  policyVersion: number;

  idempotencyKey: string;

  metadata?: Record<string, unknown>;
}

export interface MobilityCashObligationResult {
  id: string;
  organizationId: string;
  driverId: string;
  rideId: string;

  currency: string;

  grossFareMinor: string;
  commissionRateBps: number;
  commissionAmountMinor: string;

  settledAmountMinor: string;
  remainingAmountMinor: string;

  status: MobilityCashObligationStatus;

  policyKey: string;
  policyVersion: number;

  createdAt: Date;
  updatedAt: Date;
}

export interface ApplyMobilityCashSettlementInput {
  organizationId: string;

  /**
   * The driver's later digital proceeds that can be
   * used to settle previous cash obligations.
   *
   * This is NOT itself the financial transaction.
   * The financial transaction remains owned by the
   * Financial Core.
   */
  availableDigitalProceedsMinor: bigint;

  /**
   * The commission generated by the current digital ride.
   * This is kept separate from previous cash obligations.
   */
  currentDigitalCommissionMinor: bigint;

  currency: string;

  /**
   * Stable reference to the digital payment/transaction
   * that generated the proceeds.
   */
  sourceReference: string;

  /**
   * Optional idempotency key supplied by the caller.
   */
  idempotencyKey: string;

  driverId: string;

  actorUserId?: string;

  correlationId?: string;
  requestId?: string;
  ipAddress?: string;
  userAgent?: string;

  metadata?: Record<string, unknown>;
}

export interface MobilityCashSettlementResult {
  driverId: string;
  currency: string;

  availableDigitalProceedsMinor: string;
  currentDigitalCommissionMinor: string;

  priorCashObligationsSettledMinor: string;

  totalDeductedMinor: string;

  driverNetProceedsMinor: string;

  remainingCashObligationMinor: string;

  settlements: Array<{
    obligationId: string;
    rideId: string;
    amountMinor: string;
    remainingObligationMinor: string;
  }>;
}

export interface MobilityCashObligationRecord {
  id: string;
  organizationId: string;
  driverId: string;
  rideId: string;
  currency: string;
  grossFareMinor: bigint;
  commissionRateBps: number;
  commissionAmountMinor: bigint;
  settledAmountMinor: bigint;
  remainingAmountMinor: bigint;
  status: MobilityCashObligationStatus;
  idempotencyKey: string;
  policyKey: string;
  policyVersion: number;
  metadata: Prisma.JsonValue | null;
  createdAt: Date;
  updatedAt: Date;
  }
