import { randomUUID } from "node:crypto";

import { Prisma } from "@prisma/client";

import { prisma } from "@/database/client/prisma";
import { IdempotencyService } from "@/core/idempotency/idempotency.service";
import { FinancialAuditService } from "@/core/audit/financial-audit.service";

import {
  type ApplyMobilityCashSettlementInput,
  type CreateMobilityCashObligationInput,
  type MobilityCashObligationRecord,
  type MobilityCashObligationResult,
  type MobilityCashObligationStatus,
  type MobilityCashSettlementResult,
} from "@/services/mobility/payments/mobility-payment.contracts";

const BPS_TOTAL = 10_000;

const OPEN_STATUSES = [
  "OPEN",
  "PARTIALLY_SETTLED",
] as const;

export class MobilityCashSettlementService {
  private readonly idempotencyService =
    new IdempotencyService();

  private readonly financialAuditService =
    new FinancialAuditService();

  /**
   * Creates the financial obligation generated by a
   * Mobility ride paid directly to the driver in cash.
   *
   * Important:
   * - MARKA does not require the driver to prepay.
   * - The driver receives the passenger's physical cash.
   * - MARKA records only the commission obligation.
   * - The obligation is later settled from digital proceeds.
   */
  async createCashObligation(
    input: CreateMobilityCashObligationInput
  ): Promise<MobilityCashObligationResult> {
    this.validateCreateInput(input);

    const requestBody = {
      organizationId: input.organizationId,
      driverId: input.driverId,
      rideId: input.rideId,
      currency: input.currency,
      grossFareMinor:
        input.grossFareMinor.toString(),
      commissionRateBps:
        input.commissionRateBps,
      commissionAmountMinor:
        input.commissionAmountMinor.toString(),
      policyKey: input.policyKey,
      policyVersion:
        input.policyVersion,
    };

    const result =
      await this.idempotencyService.execute(
        {
          key: input.idempotencyKey,
          scope:
            `mobility.cash-obligation.create:${input.organizationId}`,
          userId: input.actorUserId,
          requestBody,
        },
        async () => {
          const obligation =
            await prisma.$transaction(
              async (database) => {
                const organization =
                  await database.organization.findUnique(
                    {
                      where: {
                        id: input.organizationId,
                      },
                      select: {
                        id: true,
                        status: true,
                      },
                    }
                  );

                if (
                  !organization ||
                  organization.status !==
                    "ACTIVE"
                ) {
                  throw new Error(
                    "Mobility organization is not active."
                  );
                }

                const driver =
                  await database.mobilityDriver.findUnique(
                    {
                      where: {
                        id: input.driverId,
                      },
                      select: {
                        id: true,
                        organizationId: true,
                        status: true,
                      },
                    }
                  );

                if (!driver) {
                  throw new Error(
                    "Mobility driver was not found."
                  );
                }

                if (
                  driver.organizationId !==
                  input.organizationId
                ) {
                  throw new Error(
                    "Mobility driver does not belong to the organization."
                  );
                }

                if (
                  driver.status !== "ACTIVE"
                ) {
                  throw new Error(
                    "Mobility driver is not active."
                  );
                }

                const ride =
                  await database.mobilityRide.findUnique(
                    {
                      where: {
                        id: input.rideId,
                      },
                      select: {
                        id: true,
                        organizationId: true,
                        driverId: true,
                        status: true,
                        currency: true,
                      },
                    }
                  );

                if (!ride) {
                  throw new Error(
                    "Mobility ride was not found."
                  );
                }

                if (
                  ride.organizationId !==
                  input.organizationId
                ) {
                  throw new Error(
                    "Mobility ride does not belong to the organization."
                  );
                }

                if (
                  ride.driverId !==
                  input.driverId
                ) {
                  throw new Error(
                    "Mobility ride is not assigned to the specified driver."
                  );
                }

                if (
                  ride.currency !==
                  input.currency
                ) {
                  throw new Error(
                    "Cash obligation currency does not match the ride currency."
                  );
                }

                if (
                  ride.status !==
                  "TRIP_COMPLETED"
                ) {
                  throw new Error(
                    "A cash obligation can only be created for a completed Mobility ride."
                  );
                }

                const existing =
                  await database.mobilityCashObligation.findUnique(
                    {
                      where: {
                        rideId:
                          input.rideId,
                      },
                    }
                  );

                if (existing) {
                  if (
                    existing.idempotencyKey !==
                    input.idempotencyKey
                  ) {
                    throw new Error(
                      "A cash obligation already exists for this ride."
                    );
                  }

                  return existing;
                }

                return database.mobilityCashObligation.create(
                  {
                    data: {
                      id: randomUUID(),

                      organizationId:
                        input.organizationId,

                      driverId:
                        input.driverId,

                      rideId:
                        input.rideId,

                      currency:
                        input.currency,

                      grossFareMinor:
                        input.grossFareMinor,

                      commissionRateBps:
                        input.commissionRateBps,

                      commissionAmountMinor:
                        input.commissionAmountMinor,

                      settledAmountMinor:
                        BigInt(0),

                      remainingAmountMinor:
                        input.commissionAmountMinor,

                      status:
                        "OPEN",

                      idempotencyKey:
                        input.idempotencyKey,

                      policyKey:
                        input.policyKey,

                      policyVersion:
                        input.policyVersion,

                      metadata:
                        input.metadata
                          ? (input.metadata as Prisma.InputJsonValue)
                          : undefined,
                    },
                  }
                );
              },
              {
                isolationLevel:
                  Prisma.TransactionIsolationLevel.Serializable,
                maxWait: 5000,
                timeout: 10000,
              }
            );

          await this.financialAuditService.record({
            organizationId:
              obligation.organizationId,

            actorUserId:
              input.actorUserId,

            action:
              "MOBILITY_CASH_OBLIGATION_CREATED",

            entityType:
              "MOBILITY_CASH_OBLIGATION",

            entityId:
              obligation.id,

            correlationId:
              input.correlationId,

            requestId:
              input.requestId,

            ipAddress:
              input.ipAddress,

            userAgent:
              input.userAgent,

            metadata: {
              obligationId:
                obligation.id,

              rideId:
                obligation.rideId,

              driverId:
                obligation.driverId,

              grossFareMinor:
                obligation.grossFareMinor.toString(),

              commissionAmountMinor:
                obligation.commissionAmountMinor.toString(),

              currency:
                obligation.currency,

              policyKey:
                obligation.policyKey,

              policyVersion:
                obligation.policyVersion,

              source:
                "MOBILITY_CASH_RIDE",
            },
          });

          return {
            responseStatus: 201,
            responseBody:
              this.toResult(obligation),
            resourceType:
              "MOBILITY_CASH_OBLIGATION",
            resourceId:
              obligation.id,
          };
        }
      );

    return result.responseBody as MobilityCashObligationResult;
  }

  /**
   * Calculates and persists the automatic offset of previous
   * cash commissions against a driver's later digital proceeds.
   *
   * The current digital commission is deliberately kept separate.
   *
   * Example:
   *
   * Previous cash obligation: 1,200 AOA
   * Current digital ride commission: 600 AOA
   * Digital proceeds available: 5,000 AOA
   *
   * Result:
   * - 600 AOA current commission
   * - 1,200 AOA previous cash obligation
   * - 1,800 AOA total deduction
   * - 3,200 AOA driver proceeds
   *
   * This method records the obligation settlement ledger.
   * The actual financial transaction that moves money between
   * Financial Core accounts remains the responsibility of the
   * Financial Core transaction layer.
   */
  async applyDigitalSettlement(
    input: ApplyMobilityCashSettlementInput
  ): Promise<MobilityCashSettlementResult> {
    this.validateSettlementInput(input);

    const requestBody = {
      organizationId:
        input.organizationId,

      driverId:
        input.driverId,

      currency:
        input.currency,

      availableDigitalProceedsMinor:
        input.availableDigitalProceedsMinor.toString(),

      currentDigitalCommissionMinor:
        input.currentDigitalCommissionMinor.toString(),

      sourceReference:
        input.sourceReference,
    };

    const result =
      await this.idempotencyService.execute(
        {
          key: input.idempotencyKey,
          scope:
            `mobility.cash-obligation.settle:${input.organizationId}`,
          userId:
            input.actorUserId,
          requestBody,
        },
        async () => {
          const settlement =
            await prisma.$transaction(
              async (database) => {
                const driver =
                  await database.mobilityDriver.findUnique(
                    {
                      where: {
                        id: input.driverId,
                      },
                      select: {
                        id: true,
                        organizationId: true,
                        status: true,
                      },
                    }
                  );

                if (!driver) {
                  throw new Error(
                    "Mobility driver was not found."
                  );
                }

                if (
                  driver.organizationId !==
                  input.organizationId
                ) {
                  throw new Error(
                    "Mobility driver does not belong to the organization."
                  );
                }

                const obligations =
                  await database.mobilityCashObligation.findMany(
                    {
                      where: {
                        organizationId:
                          input.organizationId,

                        driverId:
                          input.driverId,

                        currency:
                          input.currency,

                        status: {
                          in: [
                            ...OPEN_STATUSES,
                          ],
                        },

                        remainingAmountMinor: {
                          gt: BigInt(0),
                        },
                      },

                      orderBy: [
                        {
                          createdAt:
                            "asc",
                        },
                        {
                          id:
                            "asc",
                        },
                      ],
                    }
                  );

                let available =
                  input.availableDigitalProceedsMinor;

                let previousCashSettled =
                  BigInt(0);

                const settlements:
                  MobilityCashSettlementResult["settlements"] =
                  [];

                for (
                  const obligation of obligations
                ) {
                  if (
                    available <=
                    BigInt(0)
                  ) {
                    break;
                  }

                  const amount =
                    available <
                    obligation.remainingAmountMinor
                      ? available
                      : obligation.remainingAmountMinor;

                  if (
                    amount <=
                    BigInt(0)
                  ) {
                    continue;
                  }

                  const newSettledAmount =
                    obligation.settledAmountMinor +
                    amount;

                  const newRemainingAmount =
                    obligation.remainingAmountMinor -
                    amount;

                  const newStatus =
                    newRemainingAmount ===
                    BigInt(0)
                      ? "SETTLED"
                      : "PARTIALLY_SETTLED";

                  const settlementReference =
                    `MOBILITY-CASH-SETTLEMENT-${randomUUID()
                      .replace(/-/g, "")
                      .toUpperCase()}`;

                  const settlement =
                    await database.mobilityCashObligationSettlement.create(
                      {
                        data: {
                          id: randomUUID(),

                          organizationId:
                            input.organizationId,

                          obligationId:
                            obligation.id,

                          settlementReference,

                          sourceReference:
                            input.sourceReference,

                          amountMinor:
                            amount,

                          currency:
                            input.currency,

                          metadata:
                            input.metadata
                              ? (input.metadata as Prisma.InputJsonValue)
                              : undefined,
                        },
                      }
                    );

                  await database.mobilityCashObligation.update(
                    {
                      where: {
                        id:
                          obligation.id,
                      },

                      data: {
                        settledAmountMinor:
                          newSettledAmount,

                        remainingAmountMinor:
                          newRemainingAmount,

                        status:
                          newStatus,
                      },
                    }
                  );

                  available -= amount;

                  previousCashSettled +=
                    amount;

                  settlements.push({
                    obligationId:
                      obligation.id,

                    rideId:
                      obligation.rideId,

                    amountMinor:
                      amount.toString(),

                    remainingObligationMinor:
                      newRemainingAmount.toString(),
                  });

                  await this.financialAuditService.record({
                    organizationId:
                      input.organizationId,

                    actorUserId:
                      input.actorUserId,

                    action:
                      "MOBILITY_CASH_OBLIGATION_SETTLED",

                    entityType:
                      "MOBILITY_CASH_OBLIGATION",

                    entityId:
                      obligation.id,

                    correlationId:
                      input.correlationId,

                    requestId:
                      input.requestId,

                    ipAddress:
                      input.ipAddress,

                    userAgent:
                      input.userAgent,

                    metadata: {
                      obligationId:
                        obligation.id,

                      settlementId:
                        settlement.id,

                      settlementReference,

                      sourceReference:
                        input.sourceReference,

                      driverId:
                        input.driverId,

                      rideId:
                        obligation.rideId,

                      amountMinor:
                        amount.toString(),

                      remainingAmountMinor:
                        newRemainingAmount.toString(),

                      status:
                        newStatus,

                      currency:
                        input.currency,

                      source:
                        "MOBILITY_DIGITAL_PROCEEDS",
                    },
                  });
                }

                const totalDeducted =
                  input.currentDigitalCommissionMinor +
                  previousCashSettled;

                const driverNet =
                  input.availableDigitalProceedsMinor >
                  totalDeducted
                    ? input.availableDigitalProceedsMinor -
                      totalDeducted
                    : BigInt(0);

                const remainingCashObligation =
                  await database.mobilityCashObligation.aggregate(
                    {
                      where: {
                        organizationId:
                          input.organizationId,

                        driverId:
                          input.driverId,

                        currency:
                          input.currency,

                        status: {
                          in: [
                            ...OPEN_STATUSES,
                          ],
                        },
                      },

                      _sum: {
                        remainingAmountMinor:
                          true,
                      },
                    }
                  );

                return {
                  driverId:
                    input.driverId,

                  currency:
                    input.currency,

                  availableDigitalProceedsMinor:
                    input.availableDigitalProceedsMinor.toString(),

                  currentDigitalCommissionMinor:
                    input.currentDigitalCommissionMinor.toString(),

                  priorCashObligationsSettledMinor:
                    previousCashSettled.toString(),

                  totalDeductedMinor:
                    totalDeducted.toString(),

                  driverNetProceedsMinor:
                    driverNet.toString(),

                  remainingCashObligationMinor:
                    (
                      remainingCashObligation._sum
                        .remainingAmountMinor ??
                      BigInt(0)
                    ).toString(),

                  settlements,
                };
              },
              {
                isolationLevel:
                  Prisma.TransactionIsolationLevel.Serializable,
                maxWait: 5000,
                timeout: 10000,
              }
            );

          await this.financialAuditService.record({
            organizationId:
              input.organizationId,

            actorUserId:
              input.actorUserId,

            action:
              "MOBILITY_CASH_SETTLEMENT_APPLIED",

            entityType:
              "MOBILITY_DRIVER",

            entityId:
              input.driverId,

            correlationId:
              input.correlationId,

            requestId:
              input.requestId,

            ipAddress:
              input.ipAddress,

            userAgent:
              input.userAgent,

            metadata: {
              driverId:
                input.driverId,

              sourceReference:
                input.sourceReference,

              currency:
                input.currency,

              availableDigitalProceedsMinor:
                input.availableDigitalProceedsMinor.toString(),

              currentDigitalCommissionMinor:
                input.currentDigitalCommissionMinor.toString(),

              priorCashObligationsSettledMinor:
                settlement.priorCashObligationsSettledMinor,

              totalDeductedMinor:
                settlement.totalDeductedMinor,

              driverNetProceedsMinor:
                settlement.driverNetProceedsMinor,

              remainingCashObligationMinor:
                settlement.remainingCashObligationMinor,

              settlementCount:
                settlement.settlements.length,

              source:
                "MOBILITY_FINANCIAL_ENGINE",
            },
          });

          return {
            responseStatus: 200,
            responseBody:
              settlement,
            resourceType:
              "MOBILITY_CASH_SETTLEMENT",
            resourceId:
              input.driverId,
          };
        }
      );

    return result.responseBody as MobilityCashSettlementResult;
  }

  async getDriverOutstandingBalance(
    input: {
      organizationId: string;
      driverId: string;
      currency?: string;
    }
  ): Promise<{
    driverId: string;
    currency: string;
    outstandingAmountMinor: string;
    obligationsCount: number;
  }> {
    if (
      !input.organizationId.trim() ||
      !input.driverId.trim()
    ) {
      throw new Error(
        "Organization and driver are required."
      );
    }

    const currency =
      input.currency ?? "AOA";

    if (
      !/^[A-Z]{3}$/.test(currency)
    ) {
      throw new Error(
        "Mobility currency must be a valid ISO 4217 code."
      );
    }

    const aggregate =
      await prisma.mobilityCashObligation.aggregate(
        {
          where: {
            organizationId:
              input.organizationId,

            driverId:
              input.driverId,

            currency,

            status: {
              in: [
                ...OPEN_STATUSES,
              ],
            },

            remainingAmountMinor: {
              gt: BigInt(0),
            },
          },

          _sum: {
            remainingAmountMinor:
              true,
          },

          _count: {
            _all: true,
          },
        }
      );

    return {
      driverId:
        input.driverId,

      currency,

      outstandingAmountMinor:
        (
          aggregate._sum
            .remainingAmountMinor ??
          BigInt(0)
        ).toString(),

      obligationsCount:
        aggregate._count._all,
    };
  }

  async getDriverObligations(
    input: {
      organizationId: string;
      driverId: string;
      currency?: string;
      status?: MobilityCashObligationStatus;
    }
  ): Promise<
    MobilityCashObligationResult[]
  > {
    if (
      !input.organizationId.trim() ||
      !input.driverId.trim()
    ) {
      throw new Error(
        "Organization and driver are required."
      );
    }

    const currency =
      input.currency ?? "AOA";

    if (
      !/^[A-Z]{3}$/.test(currency)
    ) {
      throw new Error(
        "Mobility currency must be a valid ISO 4217 code."
      );
    }

    const obligations =
      await prisma.mobilityCashObligation.findMany(
        {
          where: {
            organizationId:
              input.organizationId,

            driverId:
              input.driverId,

            currency,

            status:
              input.status,
          },

          orderBy: [
            {
              createdAt:
                "asc",
            },
            {
              id:
                "asc",
            },
          ],
        }
      );

    return obligations.map(
      (obligation) =>
        this.toResult(obligation)
    );
  }

  private toResult(
    obligation: MobilityCashObligationRecord
  ): MobilityCashObligationResult {
    return {
      id:
        obligation.id,

      organizationId:
        obligation.organizationId,

      driverId:
        obligation.driverId,

      rideId:
        obligation.rideId,

      currency:
        obligation.currency,

      grossFareMinor:
        obligation.grossFareMinor.toString(),

      commissionRateBps:
        obligation.commissionRateBps,

      commissionAmountMinor:
        obligation.commissionAmountMinor.toString(),

      settledAmountMinor:
        obligation.settledAmountMinor.toString(),

      remainingAmountMinor:
        obligation.remainingAmountMinor.toString(),

      status:
        obligation.status,

      policyKey:
        obligation.policyKey,

      policyVersion:
        obligation.policyVersion,

      createdAt:
        obligation.createdAt,

      updatedAt:
        obligation.updatedAt,
    };
  }

  private validateCreateInput(
    input: CreateMobilityCashObligationInput
  ): void {
    if (
      !input.organizationId.trim()
    ) {
      throw new Error(
        "Mobility organizationId is required."
      );
    }

    if (
      !input.driverId.trim()
    ) {
      throw new Error(
        "Mobility driverId is required."
      );
    }

    if (
      !input.rideId.trim()
    ) {
      throw new Error(
        "Mobility rideId is required."
      );
    }

    if (
      !/^[A-Z]{3}$/.test(
        input.currency
      )
    ) {
      throw new Error(
        "Mobility currency must be a valid ISO 4217 code."
      );
    }

    if (
      input.grossFareMinor <
        BigInt(0)
    ) {
      throw new Error(
        "Gross fare cannot be negative."
      );
    }

    if (
      input.commissionAmountMinor <
        BigInt(0)
    ) {
      throw new Error(
        "Commission amount cannot be negative."
      );
    }

    if (
      input.commissionAmountMinor >
      input.grossFareMinor
    ) {
      throw new Error(
        "Commission cannot exceed the gross fare."
      );
    }

    if (
      !Number.isInteger(
        input.commissionRateBps
      ) ||
      input.commissionRateBps <
        0 ||
      input.commissionRateBps >
        BPS_TOTAL
    ) {
      throw new Error(
        "Commission rate must be between 0 and 10000 basis points."
      );
    }

    const calculatedCommission =
      (
        input.grossFareMinor *
        BigInt(
          input.commissionRateBps
        )
      ) /
      BigInt(BPS_TOTAL);

    if (
      calculatedCommission !==
      input.commissionAmountMinor
    ) {
      throw new Error(
        "Commission amount does not match the configured basis-point rate."
      );
    }

    if (
      !input.policyKey.trim()
    ) {
      throw new Error(
        "Commission policy key is required."
      );
    }

    if (
      !Number.isInteger(
        input.policyVersion
      ) ||
      input.policyVersion <= 0
    ) {
      throw new Error(
        "Commission policy version must be a positive integer."
      );
    }

    if (
      !input.idempotencyKey.trim()
    ) {
      throw new Error(
        "Mobility cash obligation idempotency key is required."
      );
    }
  }

  private validateSettlementInput(
    input: ApplyMobilityCashSettlementInput
  ): void {
    if (
      !input.organizationId.trim()
    ) {
      throw new Error(
        "Mobility organizationId is required."
      );
    }

    if (
      !input.driverId.trim()
    ) {
      throw new Error(
        "Mobility driverId is required."
      );
    }

    if (
      !input.currency ||
      !/^[A-Z]{3}$/.test(
        input.currency
      )
    ) {
      throw new Error(
        "Mobility currency must be a valid ISO 4217 code."
      );
    }

    if (
      input.availableDigitalProceedsMinor <
      BigInt(0)
    ) {
      throw new Error(
        "Available digital proceeds cannot be negative."
      );
    }

    if (
      input.currentDigitalCommissionMinor <
      BigInt(0)
    ) {
      throw new Error(
        "Current digital commission cannot be negative."
      );
    }

    if (
      !input.sourceReference.trim()
    ) {
      throw new Error(
        "Digital settlement source reference is required."
      );
    }

    if (
      !input.idempotencyKey.trim()
    ) {
      throw new Error(
        "Mobility cash settlement idempotency key is required."
      );
    }

    if (
      input.currentDigitalCommissionMinor >
      input.availableDigitalProceedsMinor
    ) {
      throw new Error(
        "Current digital commission cannot exceed available digital proceeds."
      );
    }
  }
}

export const mobilityCashSettlementService =
  new MobilityCashSettlementService();
