export const Permissions = {
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",

  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_UPDATE: "VENDOR_UPDATE",
  VENDOR_MANAGE: "VENDOR_MANAGE",

  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  ORDER_READ: "ORDER_READ",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_MANAGE: "ORDER_MANAGE",

  PAYMENT_PROCESS: "PAYMENT_PROCESS",

  WALLET_READ: "WALLET_READ",
  WALLET_MANAGE: "WALLET_MANAGE",

  ADMIN_ACCESS: "ADMIN_ACCESS",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
} as const;

export type PermissionAction =
  (typeof Permissions)[keyof typeof Permissions];
