export const Permissions = {
  USER_READ: "USER_READ",
  USER_UPDATE: "USER_UPDATE",

  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_UPDATE: "VENDOR_UPDATE",

  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  ORDER_CREATE: "ORDER_CREATE",
  ORDER_MANAGE: "ORDER_MANAGE",

  PAYMENT_PROCESS: "PAYMENT_PROCESS",

  ADMIN_ACCESS: "ADMIN_ACCESS",
} as const;
